product: younow

db:
  driver: "postgres"            # postgres / mysql / sqlserver ... (預設 postgres)
  conn_env: "RedshiftConnStr"

deploy:
  function_name: "SQLDB-ETL-Pipeline-Younow"
  lambda_role: "arn:aws:iam::483957310387:role/SO_ETL_Role"
  architecture: "arm64"
  timeout: 900
  memory_size: 1024
  region: "us-east-1"
  aws_profile: "younow"

reports:
  daily:
    sheet:
      name: "report"
      spreadsheet_id: "1jaq2OJKUioWb0Q6t_ft-ZEB6G60ykdXx8ryBJ3sICFs"
      write_anchor: 11
      start_search_column: "K2"
      query_parameter_range: "H:J"
    sql:
      dir: "queries/younow/daily"
